version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/faces-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/seekbar-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/tgdl-ml"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/faces-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/tgdl-ml"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/seekbar-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
